services:
  db:
    image: postgres:16-alpine
    container_name: plostre_db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Omer.0742_
      POSTGRES_DB: AtlasWebDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: 
      context: ./AtlasWeb
      dockerfile: Dockerfile
    container_name: plostre_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Host=db;Database=AtlasWebDB;Username=postgres;Password=Omer.0742_
    ports:
      - "80:8080"
    depends_on:
      - db

volumes:
  postgres_data:
