// <auto-generated />
using System;
using AtlasWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlasWeb.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260403202428_AddCariBusinessTypeField")]
    partial class AddCariBusinessTypeField
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlasWeb.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AtlasWeb.Models.Birim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "Ad")
                        .IsUnique()
                        .HasDatabaseName("IX_Birimler_MusteriId_Ad_Unique");

                    b.HasIndex("MusteriId", "Sembol")
                        .IsUnique()
                        .HasDatabaseName("IX_Birimler_MusteriId_Sembol_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Birim_SaaS_Performance");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariKart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdiSoyadi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("Belde")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid>("CariTipId")
                        .HasColumnType("uuid");

                    b.Property<int>("FaturaTipi")
                        .HasColumnType("integer");

                    b.Property<string>("GrupKodu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int?>("HksBeldeId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksIlId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksIlceId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksIsletmeTuruId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksSifatId")
                        .HasColumnType("integer");

                    b.Property<string>("Il")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Ilce")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("OzelKodu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefon2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VTCK_No")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CariTipId");

                    b.HasIndex("MusteriId", "VTCK_No")
                        .IsUnique()
                        .HasDatabaseName("IX_CariKartlar_MusteriId_VTCK_No_Unique")
                        .HasFilter("\"VTCK_No\" IS NOT NULL");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_CariKart_SaaS_Performance");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "Adi")
                        .IsUnique()
                        .HasDatabaseName("IX_CariTipler_MusteriId_Adi_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_CariTip_SaaS_Performance");

                    b.ToTable("CariTipler");
                });

            modelBuilder.Entity("AtlasWeb.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HataDetayi")
                        .HasColumnType("text");

                    b.Property<string>("HataMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IstekYolu")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AtlasWeb.Models.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("CariKartId")
                        .HasColumnType("uuid");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("FaturaTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal>("TahsilEdilenTutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("MusteriId", "FaturaNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Faturalar_MusteriId_FaturaNo_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Fatura_SaaS_Performance");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("AtlasWeb.Models.FaturaDetay", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<decimal>("BirimFiyat")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<Guid>("FaturaId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Miktar")
                        .HasPrecision(18, 3)
                        .HasColumnType("numeric(18,3)");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<decimal>("SatirToplami")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<Guid>("StokId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("FaturaId");

                    b.HasIndex("StokId");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_FaturaDetay_SaaS_Performance");

                    b.ToTable("FaturaDetaylari");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksAyar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("PasswordCipherText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ServicePasswordCipherText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksAyarlari_MusteriId_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksAyar_SaaS_Performance");

                    b.ToTable("HksAyarlari");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksBelde", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksBeldeId")
                        .HasColumnType("integer");

                    b.Property<int>("HksIlceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksBeldeId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksBeldeler_HksBeldeId_Unique");

                    b.HasIndex("HksIlceId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksBeldeler_HksIlceId_AktifMi_KayitTarihi");

                    b.ToTable("HksBeldeler");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksIl", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksIlId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksIlId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksIller_HksIlId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksIller_AktifMi_KayitTarihi");

                    b.ToTable("HksIller");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksIlce", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksIlId")
                        .HasColumnType("integer");

                    b.Property<int>("HksIlceId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksIlceId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksIlceler_HksIlceId_Unique");

                    b.HasIndex("HksIlId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksIlceler_HksIlId_AktifMi_KayitTarihi");

                    b.ToTable("HksIlceler");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksIsletmeTuru", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksIsletmeTuruId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksIsletmeTuruId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksIsletmeTurleri_HksIsletmeTuruId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksIsletmeTurleri_AktifMi_KayitTarihi");

                    b.ToTable("HksIsletmeTurleri");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksReferansKunyeKayit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Durum")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<string>("Hata")
                        .HasColumnType("text");

                    b.Property<string>("IslemKodu")
                        .HasColumnType("text");

                    b.Property<int>("KayitSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Mesaj")
                        .HasColumnType("text");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("ProgressLabel")
                        .HasColumnType("text");

                    b.Property<int>("ProgressPercent")
                        .HasColumnType("integer");

                    b.Property<string>("ReferansKunyelerJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksReferansKunyeKayitlari_MusteriId_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksReferansKunyeKayit_SaaS_Performance");

                    b.ToTable("HksReferansKunyeKayitlari");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksSifat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksSifatId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksSifatId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksSifatlar_HksSifatId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksSifatlar_AktifMi_KayitTarihi");

                    b.ToTable("HksSifatlar");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksUretimSekli", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksUretimSekliId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksUretimSekliId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksUretimSekilleri_HksUretimSekliId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksUretimSekilleri_AktifMi_KayitTarihi");

                    b.ToTable("HksUretimSekilleri");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksUrun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksUrunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksUrunId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksUrunler_HksUrunId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksUrunler_AktifMi_KayitTarihi");

                    b.ToTable("HksUrunler");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksUrunBirim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int>("HksUrunBirimId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("HksUrunBirimId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksUrunBirimleri_HksUrunBirimId_Unique");

                    b.HasIndex("AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksUrunBirimleri_AktifMi_KayitTarihi");

                    b.ToTable("HksUrunBirimleri");
                });

            modelBuilder.Entity("AtlasWeb.Models.HksUrunCinsi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<int?>("HksUretimSekliId")
                        .HasColumnType("integer");

                    b.Property<int>("HksUrunCinsiId")
                        .HasColumnType("integer");

                    b.Property<int>("HksUrunId")
                        .HasColumnType("integer");

                    b.Property<bool?>("IthalMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("UrunKodu")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HksUrunCinsiId")
                        .IsUnique()
                        .HasDatabaseName("IX_HksUrunCinsleri_HksUrunCinsiId_Unique");

                    b.HasIndex("HksUrunId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_HksUrunCinsleri_HksUrunId_AktifMi_KayitTarihi");

                    b.ToTable("HksUrunCinsleri");
                });

            modelBuilder.Entity("AtlasWeb.Models.KasaFis", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama1")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Aciklama2")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("BelgeKodu")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("BelgeNo")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CariKartId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<string>("HareketTipi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IslemTipi")
                        .HasColumnType("integer");

                    b.Property<string>("KasaAdi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("OzelKodu")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Pos")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("Tutar")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("CariKartId");

                    b.HasIndex("MusteriId", "BelgeNo")
                        .IsUnique()
                        .HasDatabaseName("IX_KasaFisleri_MusteriId_BelgeNo_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_KasaFis_SaaS_Performance");

                    b.ToTable("KasaFisleri");
                });

            modelBuilder.Entity("AtlasWeb.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("FailedLoginCount")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefon")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EPosta")
                        .IsUnique()
                        .HasDatabaseName("IX_Kullanicilar_EPosta_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Kullanici_SaaS_Performance");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AtlasWeb.Models.KullaniciSifreSifirlamaToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ConsumedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("RequestedIpAddress")
                        .HasColumnType("text");

                    b.Property<string>("TokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("TokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_KullaniciSifreSifirlamaTokenler_TokenHash_Unique");

                    b.HasIndex("KullaniciId", "ExpiryTime")
                        .HasDatabaseName("IX_KullaniciSifreSifirlamaTokenler_KullaniciId_Expiry");

                    b.ToTable("KullaniciSifreSifirlamaTokenler");
                });

            modelBuilder.Entity("AtlasWeb.Models.KullaniciToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DeviceInfo")
                        .HasColumnType("text");

                    b.Property<DateTime>("ExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("KullaniciId")
                        .HasColumnType("uuid");

                    b.Property<string>("RefreshTokenHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("RefreshTokenHash")
                        .IsUnique()
                        .HasDatabaseName("IX_KullaniciTokenler_RefreshTokenHash_Unique");

                    b.HasIndex("KullaniciId", "ExpiryTime")
                        .HasDatabaseName("IX_KullaniciTokenler_KullaniciId_Expiry");

                    b.ToTable("KullaniciTokenler");
                });

            modelBuilder.Entity("AtlasWeb.Models.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GsmNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KimlikTuru")
                        .HasColumnType("integer");

                    b.Property<string>("MusteriKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaketTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MusteriKodu")
                        .IsUnique()
                        .HasDatabaseName("IX_Musteriler_MusteriKodu_Unique");

                    b.ToTable("Musteriler");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e06c1341-3b74-4b8c-8c6e-984bb646e297"),
                            AdresDetay = "SISTEM MERKEZI",
                            AktifMi = true,
                            EPosta = "admin@atlasweb.local",
                            GsmNo = "0000000000",
                            Il = "ANKARA",
                            Ilce = "CANKAYA",
                            KayitTarihi = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            KimlikTuru = 0,
                            MusteriKodu = "ATLASWEB",
                            PaketTipi = 2,
                            Unvan = "AtlasWeb Sistem Yonetimi",
                            VergiDairesi = "SISTEM",
                            VergiNo = "00000000000"
                        });
                });

            modelBuilder.Entity("AtlasWeb.Models.Stok", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BirimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<string>("HksNitelik")
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int?>("HksUretimSekliId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksUrunCinsiId")
                        .HasColumnType("integer");

                    b.Property<int?>("HksUrunId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YedekAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("MusteriId", "StokKodu")
                        .IsUnique()
                        .HasDatabaseName("IX_Stoklar_MusteriId_StokKodu_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Stok_SaaS_Performance");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariKart", b =>
                {
                    b.HasOne("AtlasWeb.Models.CariTip", "CariTip")
                        .WithMany("CariKartlar")
                        .HasForeignKey("CariTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CariTip");
                });

            modelBuilder.Entity("AtlasWeb.Models.Fatura", b =>
                {
                    b.HasOne("AtlasWeb.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("AtlasWeb.Models.FaturaDetay", b =>
                {
                    b.HasOne("AtlasWeb.Models.Fatura", "Fatura")
                        .WithMany("Detaylar")
                        .HasForeignKey("FaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AtlasWeb.Models.Stok", "Stok")
                        .WithMany()
                        .HasForeignKey("StokId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Fatura");

                    b.Navigation("Stok");
                });

            modelBuilder.Entity("AtlasWeb.Models.KasaFis", b =>
                {
                    b.HasOne("AtlasWeb.Models.CariKart", "CariKart")
                        .WithMany()
                        .HasForeignKey("CariKartId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CariKart");
                });

            modelBuilder.Entity("AtlasWeb.Models.KullaniciSifreSifirlamaToken", b =>
                {
                    b.HasOne("AtlasWeb.Models.Kullanici", "Kullanici")
                        .WithMany("SifreSifirlamaTokenleri")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AtlasWeb.Models.KullaniciToken", b =>
                {
                    b.HasOne("AtlasWeb.Models.Kullanici", "Kullanici")
                        .WithMany("Tokens")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("AtlasWeb.Models.Stok", b =>
                {
                    b.HasOne("AtlasWeb.Models.Birim", "Birim")
                        .WithMany("Stoklar")
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("AtlasWeb.Models.Birim", b =>
                {
                    b.Navigation("Stoklar");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariTip", b =>
                {
                    b.Navigation("CariKartlar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Fatura", b =>
                {
                    b.Navigation("Detaylar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Kullanici", b =>
                {
                    b.Navigation("SifreSifirlamaTokenleri");

                    b.Navigation("Tokens");
                });
#pragma warning restore 612, 618
        }
    }
}
