using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlasWeb.Migrations
{
    public partial class AddCariKartAndCariTip : Migration
    {
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // --- 1. MUSTERILER TABLOSU GÜNCELLEMELERÝ ---
            migrationBuilder.Sql(@"
                DO $$ BEGIN 
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Musteriler' AND column_name = 'PaketTipi' AND data_type = 'text') THEN
                        ALTER TABLE ""Musteriler"" ALTER COLUMN ""PaketTipi"" TYPE integer USING ""PaketTipi""::integer;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Musteriler' AND column_name = 'KimlikTuru' AND data_type = 'text') THEN
                        ALTER TABLE ""Musteriler"" ALTER COLUMN ""KimlikTuru"" TYPE integer USING ""KimlikTuru""::integer;
                    END IF;
                END $$;");

            // --- 2. KULLANICILAR TABLOSU GÜNCELLEMELERÝ ---
            migrationBuilder.Sql(@"
                DO $$ BEGIN 
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Kullanicilar' AND column_name = 'Soyad' AND character_maximum_length IS NOT NULL) THEN
                        ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""Soyad"" TYPE text;
                    END IF;
                    IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_name = 'Kullanicilar' AND column_name = 'Ad' AND character_maximum_length IS NOT NULL) THEN
                        ALTER TABLE ""Kullanicilar"" ALTER COLUMN ""Ad"" TYPE text;
                    END IF;
                END $$;");

            // --- 3. FATURALAR ID DÖNÜÞÜMÜ (HATA VEREN KRÝTÝK KISIM) ---
            // EF Core'un kendi AlterColumn metodunu kullanmýyoruz çünkü hatalý DROP IDENTITY üretiyor.
            migrationBuilder.Sql(@"
                DO $$ BEGIN 
                    -- Identity'i kaldýr (Sadece varsa)
                    IF EXISTS (SELECT 1 FROM information_schema.columns 
                               WHERE table_name = 'Faturalar' AND column_name = 'Id' AND is_identity = 'YES') THEN
                        ALTER TABLE ""Faturalar"" ALTER COLUMN ""Id"" DROP IDENTITY;
                    END IF;
                    
                    -- Tipi UUID'ye çevir (Sadece hala integer ise)
                    IF (SELECT data_type FROM information_schema.columns WHERE table_name = 'Faturalar' AND column_name = 'Id') = 'integer' THEN
                        ALTER TABLE ""Faturalar"" ALTER COLUMN ""Id"" TYPE uuid USING (md5(""Id""::text)::uuid);
                    END IF;
                END $$;");

            // --- 4. YENÝ TABLOLARIN OLUÞTURULMASI (GÜVENLÝ) ---
            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"AuditLogs\" ( \"Id\" uuid NOT NULL, \"EntityName\" text NOT NULL, \"EntityId\" text NOT NULL, \"Action\" text NOT NULL, \"UserId\" text, \"Timestamp\" timestamp with time zone NOT NULL, CONSTRAINT \"PK_AuditLogs\" PRIMARY KEY (\"Id\") );");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"Birimler\" ( \"Id\" uuid NOT NULL, \"Ad\" text NOT NULL, \"Sembol\" text NOT NULL, \"AktifMi\" boolean NOT NULL, \"SilinmeTarihi\" timestamp with time zone, \"SilenKullanici\" text, \"KayitTarihi\" timestamp with time zone NOT NULL, \"OlusturanKullanici\" text, \"GuncellemeTarihi\" timestamp with time zone, \"GuncelleyenKullanici\" text, \"Source\" integer NOT NULL, CONSTRAINT \"PK_Birimler\" PRIMARY KEY (\"Id\") );");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"CariTipler\" ( \"Id\" uuid NOT NULL, \"Adi\" character varying(50) NOT NULL, \"Aciklama\" character varying(200), \"AktifMi\" boolean NOT NULL, \"SilinmeTarihi\" timestamp with time zone, \"SilenKullanici\" text, \"KayitTarihi\" timestamp with time zone NOT NULL, \"OlusturanKullanici\" text, \"GuncellemeTarihi\" timestamp with time zone, \"GuncelleyenKullanici\" text, \"Source\" integer NOT NULL, CONSTRAINT \"PK_CariTipler\" PRIMARY KEY (\"Id\") );");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"ErrorLogs\" ( \"Id\" integer GENERATED BY DEFAULT AS IDENTITY, \"HataMesaji\" text NOT NULL, \"HataDetayi\" text, \"IstekYolu\" text, \"KullaniciId\" text, \"Tarih\" timestamp with time zone NOT NULL, CONSTRAINT \"PK_ErrorLogs\" PRIMARY KEY (\"Id\") );");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"Stoklar\" ( \"Id\" uuid NOT NULL, \"StokKodu\" text NOT NULL, \"StokAdi\" text NOT NULL, \"YedekAdi\" text, \"BirimId\" uuid NOT NULL, \"MusteriId\" uuid NOT NULL, \"AktifMi\" boolean NOT NULL, \"KayitTarihi\" timestamp with time zone NOT NULL, \"OlusturanKullanici\" text, \"GuncellemeTarihi\" timestamp with time zone, \"GuncelleyenKullanici\" text, \"SilinmeTarihi\" timestamp with time zone, \"SilenKullanici\" text, \"Source\" integer NOT NULL, CONSTRAINT \"PK_Stoklar\" PRIMARY KEY (\"Id\"), CONSTRAINT \"FK_Stoklar_Birimler_BirimId\" FOREIGN KEY (\"BirimId\") REFERENCES \"Birimler\" (\"Id\") ON DELETE CASCADE );");

            migrationBuilder.Sql("CREATE TABLE IF NOT EXISTS \"CariKartlar\" ( \"Id\" uuid NOT NULL, \"CariTipId\" uuid NOT NULL, \"Unvan\" character varying(150), \"AdiSoyadi\" character varying(100), \"FaturaTipi\" integer NOT NULL, \"GrupKodu\" character varying(20), \"OzelKodu\" character varying(20), \"Telefon\" character varying(20), \"Telefon2\" character varying(20), \"Gsm\" character varying(20), \"Adres\" character varying(250), \"VergiDairesi\" character varying(50), \"VTCK_No\" character varying(11), \"MusteriId\" uuid NOT NULL, \"AktifMi\" boolean NOT NULL, \"KayitTarihi\" timestamp with time zone NOT NULL, \"OlusturanKullanici\" text, \"GuncellemeTarihi\" timestamp with time zone, \"GuncelleyenKullanici\" text, \"SilinmeTarihi\" timestamp with time zone, \"SilenKullanici\" text, \"Source\" integer NOT NULL, CONSTRAINT \"PK_CariKartlar\" PRIMARY KEY (\"Id\"), CONSTRAINT \"FK_CariKartlar_CariTipler_CariTipId\" FOREIGN KEY (\"CariTipId\") REFERENCES \"CariTipler\" (\"Id\") ON DELETE RESTRICT );");

            // --- 5. INDEXLER (GÜVENLÝ) ---
            migrationBuilder.Sql("CREATE UNIQUE INDEX IF NOT EXISTS \"IX_Faturalar_MusteriId_FaturaNo_Unique\" ON \"Faturalar\" (\"MusteriId\", \"FaturaNo\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_CariKart_SaaS_Performance\" ON \"CariKartlar\" (\"MusteriId\", \"AktifMi\", \"KayitTarihi\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_CariKartlar_CariTipId\" ON \"CariKartlar\" (\"CariTipId\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Stok_SaaS_Performance\" ON \"Stoklar\" (\"MusteriId\", \"AktifMi\", \"KayitTarihi\");");
            migrationBuilder.Sql("CREATE INDEX IF NOT EXISTS \"IX_Stoklar_BirimId\" ON \"Stoklar\" (\"BirimId\");");
        }

        protected override void Down(MigrationBuilder migrationBuilder)
        {
            // Down metodu isteðe baðlýdýr, þu anlýk boþ býrakabilirsin.
        }
    }
}