// <auto-generated />
using System;
using AtlasWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlasWeb.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    [Migration("20260324224424_AddCariKartAndCariTip")]
    partial class AddCariKartAndCariTip
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlasWeb.Models.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("UserId")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("AtlasWeb.Models.Birim", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("Sembol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Birimler");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariKart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdiSoyadi")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Adres")
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CariTipId")
                        .HasColumnType("uuid");

                    b.Property<int>("FaturaTipi")
                        .HasColumnType("integer");

                    b.Property<string>("GrupKodu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Gsm")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("OzelKodu")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Telefon")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefon2")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Unvan")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("VTCK_No")
                        .HasMaxLength(11)
                        .HasColumnType("character varying(11)");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("Id");

                    b.HasIndex("CariTipId");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_CariKart_SaaS_Performance");

                    b.ToTable("CariKartlar");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariTip", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Aciklama")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("CariTipler");
                });

            modelBuilder.Entity("AtlasWeb.Models.ErrorLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("HataDetayi")
                        .HasColumnType("text");

                    b.Property<string>("HataMesaji")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IstekYolu")
                        .HasColumnType("text");

                    b.Property<string>("KullaniciId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("ErrorLogs");
                });

            modelBuilder.Entity("AtlasWeb.Models.Fatura", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "FaturaNo")
                        .IsUnique()
                        .HasDatabaseName("IX_Faturalar_MusteriId_FaturaNo_Unique");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Fatura_SaaS_Performance");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Kullanici_SaaS_Performance");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GsmNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("KimlikTuru")
                        .HasColumnType("integer");

                    b.Property<string>("MusteriKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PaketTipi")
                        .HasColumnType("integer");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });

            modelBuilder.Entity("AtlasWeb.Models.Stok", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<Guid>("BirimId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("StokAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("StokKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("YedekAdi")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BirimId");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Stok_SaaS_Performance");

                    b.ToTable("Stoklar");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariKart", b =>
                {
                    b.HasOne("AtlasWeb.Models.CariTip", "CariTip")
                        .WithMany("CariKartlar")
                        .HasForeignKey("CariTipId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CariTip");
                });

            modelBuilder.Entity("AtlasWeb.Models.Stok", b =>
                {
                    b.HasOne("AtlasWeb.Models.Birim", "Birim")
                        .WithMany()
                        .HasForeignKey("BirimId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Birim");
                });

            modelBuilder.Entity("AtlasWeb.Models.CariTip", b =>
                {
                    b.Navigation("CariKartlar");
                });
#pragma warning restore 612, 618
        }
    }
}
