// <auto-generated />
using System;
using AtlasWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AtlasWeb.Migrations
{
    [DbContext(typeof(AtlasDbContext))]
    partial class AtlasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AtlasWeb.Models.Fatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("FaturaNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<decimal>("Tutar")
                        .HasColumnType("numeric");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Fatura_SaaS_Performance");

                    b.ToTable("Faturalar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Kullanici", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("GuncellemeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("GuncelleyenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("MusteriId")
                        .HasColumnType("uuid");

                    b.Property<string>("OlusturanKullanici")
                        .HasColumnType("text");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SilenKullanici")
                        .HasColumnType("text");

                    b.Property<DateTime?>("SilinmeTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Source")
                        .HasColumnType("integer");

                    b.Property<string>("Soyad")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("MusteriId", "AktifMi", "KayitTarihi")
                        .HasDatabaseName("IX_Kullanici_SaaS_Performance");

                    b.ToTable("Kullanicilar");
                });

            modelBuilder.Entity("AtlasWeb.Models.Musteri", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AdresDetay")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("boolean");

                    b.Property<string>("EPosta")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("GsmNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Il")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ilce")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("KayitTarihi")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("KimlikTuru")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MusteriKodu")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PaketTipi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Unvan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiDairesi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VergiNo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Musteriler");
                });
#pragma warning restore 612, 618
        }
    }
}
